name: Smoke Tests (Chrome)

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests
        default: https://demoqa.com/webtables

jobs:
  SmokeTests_Chrome:
    name: Run SmokeTests on Chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run SmokeTests
        run: |
          export BROWSER=chrome
          export GRID_URL=${{ github.event.inputs.grid_url }}

          mvn test -q -Dgroups=SmokeTests
