name: Selenium tests

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests
        default: https://demoqa.com/webtables

      chrome_131_0:
        description: 'Chrome (131.0)'
        required: false
        type: boolean

      run_smoke_tests:
        description: 'Run only SmokeTests'
        required: false
        type: boolean

jobs:
  TestChrome_131_0:
    name: Test Chrome 131.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome_131_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Tests
        run: |
          export BROWSER=chrome
          export GRID_URL=${{ github.event.inputs.grid_url }}

          if [ "${{ github.event.inputs.run_smoke_tests }}" == "true" ]; then
            mvn test -q -Dgroups=SmokeTests
          else
            mvn test -q
          fi
